### ISSUE TITLE
Parse error: syntax error

### ISSUE THREAD

**Issue by goose2288** [OliverLeitner/pickemschedules#1]
Getting this error when running tool...

Parse error: syntax error, unexpected '.', expecting variable (T_VARIABLE) in /home2/******/public_html/pickemschedules/libs/vendor/symfony/polyfill-mbstring/bootstrap.php on line 119

any ideas??

**Comment by OliverLeitner** [comment]
hello goose2288

thank you for reporting this.
i have a few questions:

1. which php version are you using?
2. do you have mbstring extension for your php version installed?

the php version on that container i am doing this in: 8.0.10
